apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: labs-authoring-guides
spec:
  portal:
    title: Workshop Authoring
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
    workshop:
      defaults:
        reserved: 1
        initial: 0
        expires: 30m
        overtime: 10m
        deadline: 60m
        orphaned: 5m
  workshops:
    - name: lab-authoring-environment
